---
# In Kubernetes a deployment is used to manange pods.
# For this task, you should have one deployment for the backend code execution
# API so the number of replications can be increased / decreased independently.
#
#
# https://v1-8.docs.kubernetes.io/docs/concepts/workloads/controllers/deployment/
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: project22task4-gke
  labels:
    app: task4-gke
# You should complete this spec field based on the deployment spec defined in:
# https://v1-8.docs.kubernetes.io/docs/concepts/workloads/controllers/deployment/
spec:
  replicas: 1
  selector:
    matchLabels:
      app: task4-gke
  template:
    metadata:
      labels:
        app: task4-gke
      namespace:
    spec:
      containers:
        - name: task4-gke-app
          image: gcr.io/nimble-radio-214818/task4:server
          ports:
          - containerPort: 6000
---
# For this task, you should have one deployment for the frontend code execution UI
# so the number of replications can be increased / decreased independently.
#
#
# https://v1-8.docs.kubernetes.io/docs/concepts/workloads/controllers/deployment/
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: project22task4-gke-frontend
  labels:
    app: task4-gke-frontend
# You should complete this spec field based on the deployment spec defined in:
# https://v1-8.docs.kubernetes.io/docs/concepts/workloads/controllers/deployment/
spec:
  replicas: 1
  selector:
    matchLabels:
      app: task4-gke-frontend
  template:
    metadata:
      labels:
        app: task4-gke-frontend
      namespace:
    spec:
      containers:
        - name: task4-gke-frontend-app
          image: gcr.io/nimble-radio-214818/task4:ui
          ports:
          - containerPort: 5000
---
# A service is an abstraction that enables traffic to be routed from the network to a
# specific pod. This service should double as a Load Balancer.
# https://kubernetes.io/docs/concepts/services-networking/service/
#
#
# You should create a service for each deployment you have created above.
# https://v1-8.docs.kubernetes.io/docs/concepts/services-networking/service/#type-loadbalancer
apiVersion: v1
kind: Service
metadata:
  name: project22task4-gke
  labels:
    app: task4-gke
# Complete the service spec based on the documentation provided in:
# https://v1-8.docs.kubernetes.io/docs/api-reference/v1.8/#service-v1-core
spec:
  selector:
    app: task4-gke
  ports:
  - port: 80
    targetPort: 6000
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: project22task4-gke-frontend
  labels:
    app: task4-gke-frontend
spec:
  selector:
    app: task4-gke-frontend
  ports:
  - port: 80
    targetPort: 5000
  type: LoadBalancer
