---
# In Kubernetes a deployment is used to manange pods.
# For this task, you should have one deployment for the backend code execution
# API so the number of replications can be increased / decreased independently.
#
#
# https://v1-8.docs.kubernetes.io/docs/concepts/workloads/controllers/deployment/
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: project22task5-gke
  labels:
    app: task5-gke
# You should complete this spec field based on the deployment spec defined in:
# https://v1-8.docs.kubernetes.io/docs/concepts/workloads/controllers/deployment/
spec:
  replicas: 1
  selector:
    matchLabels:
      app: task5-gke
  template:
    metadata:
      labels:
        app: task5-gke
      namespace:
    spec:
      containers:
        - name: task5-gke-app
          image: gcr.io/nimble-radio-214818/task5:server
          ports:
          - containerPort: 6000
          resources:
            requests:
              cpu: "100m"
---
# For this task, you should have one deployment for the frontend code execution UI
# so the number of replications can be increased / decreased independently.
#
#
# https://v1-8.docs.kubernetes.io/docs/concepts/workloads/controllers/deployment/
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: project22task5-gke-frontend
  labels:
    app: task5-gke-frontend
# You should complete this spec field based on the deployment spec defined in:
# https://v1-8.docs.kubernetes.io/docs/concepts/workloads/controllers/deployment/
spec:
  replicas: 1
  selector:
    matchLabels:
      app: task5-gke-frontend
  template:
    metadata:
      labels:
        app: task5-gke-frontend
      namespace:
    spec:
      containers:
        - name: task5-gke-frontend
          image: gcr.io/nimble-radio-214818/task5:ui
          ports:
          - containerPort: 5000
          resources:
            requests:
              cpu: "100m"
---
# A service is an abstraction that enables traffic to be routed from the network to a
# specific pod. This service should double as a Load Balancer.
# https://kubernetes.io/docs/concepts/services-networking/service/
#
#
# You should create a service for each deployment you have created above.
# https://v1-8.docs.kubernetes.io/docs/concepts/services-networking/service/#type-loadbalancer
apiVersion: v1
kind: Service
metadata:
  name: project22task5-gke
  labels:
    app: task5-gke
# Complete the service spec based on the documentation provided in:
#    https://v1-8.docs.kubernetes.io/docs/api-reference/v1.8/#service-v1-core
spec:
  selector:
    app: task5-gke
  ports:
  - port: 80
    targetPort: 6000
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: project22task5-gke-frontend
  labels:
    app: task5-gke-frontend
spec:
  selector:
    app: task5-gke-frontend
  ports:
  - port: 80
    targetPort: 5000
  type: LoadBalancer
---
# For this task you will need to define autoscaling rules pers the write up
# to ensure that the backend pod does not exceed a certain cpu utilization.
#
# https://v1-8.docs.kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale-walkthrough/
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: task5-gke-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: project22task5-gke
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 50
---
# For this task you will need to define autoscaling rules pers the write up
# to ensure that the frontend pod does not exceed a certain cpu utilization.
#
# https://v1-8.docs.kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale-walkthrough/
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: task5-gke-frontend-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: project22task5-gke-frontend
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 50